### ISSUE TITLE
alert width

### ISSUE THREAD

**Issue by vadimsidorov** [vadimsidorov/AAA-app#10]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/39313062/191364121-c57ff02f-4203-4e57-b4ca-687fe6b428a8.png">
alert width should not exceed width of form (create scss variables so that width is not duplicated)

**Comment by ska7** [comment]
@vadimsidorov this is fixed here - https://github.com/vadimsidorov/AAA-app/pull/12
