### ISSUE TITLE
Create a logo 

### ISSUE THREAD

**Issue by marianko77** [vadimsidorov/AAA-app#8]
Create main company logo

**Comment by marianko77** [comment]
Replace current logo on top of website  **from:**
<img width="220" alt="Screen Shot 2022-09-17 at 3 52 05 PM" src="https://user-images.githubusercontent.com/113124081/190874259-8982360c-7f12-443a-9c3f-b4d907755514.png">
**to:** 
![Untitled design](https://user-images.githubusercontent.com/113124081/190874395-6007f853-f83b-4aca-b74e-c893c71479fe.svg)

And replace text from Luaz to Alien Express LLC

**Comment by marianko77** [comment]
Color can inverted by applying property filter: invert(1)

**Comment by marianko77** [comment]
It was closed dog, I just reopened @vadimsidorov @ska7

**Comment by ska7** [comment]
@vadimsidorov https://github.com/vadimsidorov/AAA-app/pull/14

**Comment by vadimsidorov** [comment]
please find here optimized svg
![aaa-logo](https://user-images.githubusercontent.com/39313062/192011981-9bb791d3-eb0f-4abd-8491-3ae0a545883d.svg)
